--V1: Migration para criar tabelas tb_missoes e tb_cadastro
CREATE TABLE tb_missoes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255),
    dificuldade VARCHAR(255)
);

CREATE TABLE tb_cadastro (
     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     nome VARCHAR(255),
     email VARCHAR(255) UNIQUE,
     idade INTEGER,
     missoes_id BIGINT,
     img_url VARCHAR(255),

     CONSTRAINT fk_cadastro_missao
         FOREIGN KEY (missoes_id)
         REFERENCES tb_missoes(id)
);